// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSpeedrunApi.Types.Database;

#nullable disable

namespace SchoolSpeedrunApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SchoolSpeedrunApi.Types.Database.DbLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SchoolSpeedrunApi.Types.Database.DbRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardGuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Scanned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("SchoolSpeedrunApi.Types.Database.DbRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinishDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Milliseconds")
                        .HasColumnType("REAL");

                    b.Property<int>("StartLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndLocationId");

                    b.HasIndex("StartLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("SchoolSpeedrunApi.Types.Database.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardGuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolProgram")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SchoolSpeedrunApi.Types.Database.DbLocation", b =>
                {
                    b.HasOne("SchoolSpeedrunApi.Types.Database.DbUser", "User")
                        .WithMany("Locations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolSpeedrunApi.Types.Database.DbRun", b =>
                {
                    b.HasOne("SchoolSpeedrunApi.Types.Database.DbLocation", "EndLocation")
                        .WithMany("EndRuns")
                        .HasForeignKey("EndLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSpeedrunApi.Types.Database.DbLocation", "StartLocation")
                        .WithMany("StartRuns")
                        .HasForeignKey("StartLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolSpeedrunApi.Types.Database.DbUser", "User")
                        .WithMany("Runs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndLocation");

                    b.Navigation("StartLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SchoolSpeedrunApi.Types.Database.DbLocation", b =>
                {
                    b.Navigation("EndRuns");

                    b.Navigation("StartRuns");
                });

            modelBuilder.Entity("SchoolSpeedrunApi.Types.Database.DbUser", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
